var bbcode = ['[size=3]Configuration Output[/size]',
    '',
    '[size=2]Summary[/size]',
    '',
    '[size=-1][b]Primary stats[/b]',
    '[indent]Hitpoints: [b]10688[/b][/indent]',
    '[indent]Combat Power: [b]504[/b][/indent]',
    '[indent]Attack Rating: [b]1565[/b][/indent]',
    '[indent]Weapon Power: [b]457[/b][/indent]',
    '[indent]Heal Rating: [b]0[/b][/indent]',
    '[b]Offensive stats[/b]',
    '[indent]Critical Rating: [b][color=green]0[/color][/b][/indent]',
    '[indent]Critical Chance: [b][color=green]5.00 %[/color][/b][/indent]',
    '[indent]Critical Power Rating: [b][color=green]0[/color][/b][/indent]',
    '[indent]Critical Power: [b][color=green]25.00 %[/color][/b][/indent]',
    '[indent]Penetration Rating: [b][color=green]0[/color][/b][/indent]',
    '[indent]Hit Rating: [b][color=green]504[/color][/b][/indent]',
    '[b]Defensive stats[/b]',
    '[indent]Block Rating: [b][color=green]691[/color][/b][/indent]',
    '[indent]Defense Rating: [b][color=green]576[/color][/b][/indent]',
    '[indent]Evade Rating: [b][color=green]0[/color][/b][/indent]',
    '[indent]Physical Protection: [b][color=green]609[/color][/b][/indent]',
    '[indent]Magical Protection: [b][color=green]249[/color][/b][/indent]',
    '[/size]',
    '',
    '[size=2]Gear report[/size]',
    '',
    '[size=-1][b]Weapon (QL [color=purple]10.5[/color])[/b] [b][color=green]+457[/color][/b] Weapon Power',
    '[indent]Glyph (QL [color=purple]10.4[/color]): Hit-rating [b][color=green]+319[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=blue]Elite[/color]): Signet of [b]Fury[/b]. When you achieve 10 hits you gain 10% damage increase for 6 seconds. 6 seconds cooldown.[/indent]',
    '[b]Head (QL [color=purple]10.4[/color] Tank)[/b] [b][color=green]+2476[/color][/b] Hitpoints',
    '[indent]Glyph (QL [color=purple]10.5[/color]): Block-rating [b][color=green]+363[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=purple]Epic[/color]): Signet of [b]Order[/b]. When you block you gain 45% block chance for 4 seconds. 10 seconds cooldown.[/indent]',
    '[b]Ring (QL [color=purple]10.4[/color] Dps)[/b] [b][color=green]+664[/color][/b] Attack Rating',
    '[indent]Glyph (QL [color=purple]10.4[/color]): Defense-rating [b][color=green]+288[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=blue]Elite[/color]): Signet of [b]Vigour[/b]. Your health is increased by 330.[/indent]',
    '[b]Neck (QL [color=purple]10.4[/color] Tank)[/b] [b][color=green]+2237[/color][/b] Hitpoints',
    '[indent]Glyph (QL [color=purple]10.5[/color]): Block-rating [b][color=green]+328[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=green]Normal[/color]): Signet of [b]Violence[/b]. Your attack rating is increased by 47.[/indent]',
    '[b]Wrist (Brooklyn Bracer)[/b] [b][color=green]+2237[/color][/b] Hitpoints',
    '[indent]Glyph (QL [color=purple]10.4[/color]): Defense-rating [b][color=green]+288[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=purple]Epic[/color]): Whenever you are attacked, you gain a single stack of a beneficial effect that increases your Evade Chance by 5% per stack. This effect is removed after you successfully evade. 6 seconds cooldown.[/indent]',
    '[b]Luck (QL [color=purple]10.4[/color] Dps)[/b] [b][color=green]+427[/color][/b] Attack Rating',
    '[indent]Glyph (QL [color=purple]10.4[/color]): Physical-protection [b][color=green]+180[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=purple]Epic[/color]): Signet of [b]Ablation[/b]. When your health is below 50% the next 5 hits against you do 25% less damage. 12 seconds cooldown.[/indent]',
    '[b]Waist (NY Buckle)[/b] [b][color=green]+1438[/color][/b] Hitpoints',
    '[indent]Glyph (QL [color=purple]10.4[/color]): Physical-protection [b][color=green]+180[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=purple]Epic[/color]): Every 6 seconds, you gain a single stack of a beneficial effect that increases your Physical and Magical Protection by 3% per stack. This effect is removed whenever you are penetrated or the number of stacks exceeds 10.[/indent]',
    '[b]Occult (QL [color=purple]10.4[/color] Dps)[/b] [b][color=green]+427[/color][/b] Attack Rating',
    '[indent]Glyph (QL [color=purple]10.4[/color]): Hit-rating [b][color=green]+185[/color][/b] (4/4)[/indent]',
    '[indent]Signet ([color=purple]Epic[/color]): Signet of [b]Salvation[/b]. When you Block, Evade, or are Glanced, you gain 6% damage reduction for 5 seconds. 6 seconds cooldown.[/indent]',
    '[/size]'].join('\n');